name: Build project

on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "build linux"
        run: |
          mkdir build
          bash build.sh .
      - name: Upload linux
        uses: actions/upload-artifact@v4
        with:
          name: P1-meter app
          path: build/p1-meter
